import "./globals.css";
import "@fontsource/poppins"; // Defaults to 400 weight
import '@mantine/core/styles.css';
import HydrationProvider from "./HydrationProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactQueryProvider } from "@/provider/react-query";
import { ColorSchemeScript, createTheme, MantineProvider, mantineHtmlProps } from '@mantine/core';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Petshop Manager",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: "Arial",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HydrationProvider>
          <MantineProvider theme={theme} defaultColorScheme="dark">
            <ReactQueryProvider>
              <main>
                {children}
              </main>
            </ReactQueryProvider>
          </MantineProvider>
        </HydrationProvider>
      </body>
    </html>
  );
}